baseURL: https://tushgaurav.in/
languageCode: en-us
title: Tushar Gaurav Blogs
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Chat
          url: chat/
          weight: 0

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Tushar Gaurav Blogs"
  author: Tushar Gaurav
  # author: ["Me", "You"] # multiple authors

  defaultTheme: dark
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  comments: false
  images: ["papermod-cover.png"]

  profileMode:
    enabled: false
    title: "About Me"
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hello World, Meet My Mistakes"
    Content: "
      I'm a software developer and graphic designer focused on clean, effective solutions.
      My passion lies in creating seamless user experiences and visually appealing designs.
      Off the desk, I'm all about tech trends and a bit of humor.
      "

  socialIcons:
    - name: github
      url: "https://github.com/tushgaurav"
    - name: email
      url: "mailto:hello@tushgaurav.in"
    - name: linkedin
      url: "https://www.linkedin.com/in/tushgaurav/"
    - name: behance
      url: "https://www.behance.net/tushgaurav"
    - name: Rss
      url: "index.xml"

  editPost:
    URL: "https://github.com/tushgaurav/tushgaurav.in/tree/main/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  label:
    text: "tushgaurav"
    icon: icon.png
    iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
    favicon: "/favicon.png"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    # safari_pinned_tab: "<link / abs url>"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
